---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: latest

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: server
    run_list:
      - recipe[openvpn::server]
    attributes:
      openvpn:
        config:
          verb: 1
          mute: 10
        push_routes:
          - 192.168.10.0 255.255.255.0
        push_options:
          dhcp-option:
          - 'DOMAIN local'
          - 'DOMAIN-SEARCH local'
