---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true
  
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: centos-6.4
    run_list:
      - 'recipe[yum-epel::default]'

suites:
  - name: server
    run_list:
      - recipe[openvpn::default]
    attributes: {}
