---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: server
    run_list:
      - recipe[test]
    attributes:
      openvpn:
        config:
          verb: 1
          mute: 10
