sudo: false

language: ruby

rvm:
  - 2.2.0
  - 2.1.5
  - 2.0.0-p598

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"

install: travis_wait bundle install --without development integration

script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop --version
  - bundle exec rubocop
  - bundle exec rspec --color --format progress
